-- 1. Crear tabla de configuración
create table public.site_config (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar RLS
alter table public.site_config enable row level security;

-- 3. Políticas de seguridad (RLS)
-- Todos pueden leer (para que el sitio cargue)
create policy "Public Config Read Access" 
  on public.site_config for select 
  using (true);

-- Solo usuarios autenticados pueden insertar/actualizar (Admin)
create policy "Admin Config Write Access" 
  on public.site_config for insert 
  with check (auth.role() = 'authenticated');

create policy "Admin Config Update Access" 
  on public.site_config for update 
  using (auth.role() = 'authenticated');

-- 4. Insertar valores iniciales (Placeholders para que existan las keys)
insert into public.site_config (key, value, description) values
  ('navbar_logo_url', '', 'URL del logo en la barra de navegación'),
  ('hero_logo_url', '', 'URL de la imagen "Llegó el Inge"'),
  ('hero_main_image_url', '', 'URL de la imagen principal del Hero'),
  ('about_bg_url', '', 'URL de la imagen de perfil en "Sobre Mí"'),
  ('about_content', '', 'Contenido de texto de la sección "Sobre Mí"');

-- 5. Crear Bucket de Storage para imágenes del sitio
-- Nota: Deberás crear el bucket 'site-assets' manualmente desde el dashboard si este script falla en la creación de buckets, 
-- pero las políticas sí se pueden aplicar aquí.

insert into storage.buckets (id, name, public) 
values ('site-assets', 'site-assets', true)
on conflict (id) do nothing;

create policy "Images Public Access"
  on storage.objects for select
  using ( bucket_id = 'site-assets' );

create policy "Admin Images Upload Access"
  on storage.objects for insert
  with check ( bucket_id = 'site-assets' and auth.role() = 'authenticated' );

create policy "Admin Images Update Access"
  on storage.objects for update
  using ( bucket_id = 'site-assets' and auth.role() = 'authenticated' );
